### ISSUE TITLE
Gecerliligini yitirmis hatasi.

### ISSUE THREAD

**Issue by frkn-aydn** [kahvedigital/iyzico-woocommerce#11]
**Taksitli olarak odeme butonuna basinca asagidaki resimlerdeki hatalari almaktayiz...**

![alt text](https://i.hizliresim.com/POR9Md.jpg "1")
![alt text](https://i.hizliresim.com/7yOzvL.jpg "1")
![alt text](https://i.hizliresim.com/rJqr9a.jpg "1")

**Comment by utkuturna** [comment]
#12

**Comment by kahvedigital** [comment]
Woocommerce Güncellemesi yapıldı.
