### ISSUE TITLE
Customer payment page error (empty)

### ISSUE THREAD

**Issue by ghost** [kahvedigital/iyzico-woocommerce#15]
Hi there, whenever payment will be re-initiated by clicking the 'pay' link in the account or admin page Iyzico payment is not working (blank page after selecting Iyzico payment). Any help highly appreciated. BR...Holger

Selecting payment:
<img width="710" alt="screen shot 2018-03-11 at 12 58 08" src="https://user-images.githubusercontent.com/5089403/37252093-66a59794-252c-11e8-910b-c6f18542c21d.png">

Iyzico payment screen empty:
<img width="758" alt="screen shot 2018-03-11 at 12 59 57" src="https://user-images.githubusercontent.com/5089403/37252082-4191138e-252c-11e8-86b8-db8881263e5b.png">

**Comment by ramiassi** [comment]
try displaying errors first. in your wp-config.php use:
`define('WP_DEBUG', true);`
if you get error like this:
`Catchable fatal error: Object of class Iyzipay\Model\CheckoutFormInitialize could not be converted to string in \wp-includes\pomo\entry.php on line 76`

It's probably an SSL problem in your website. you can temporarily disable ssl verification by adding this line of code:
`CURLOPT_SSL_VERIFYPEER => false`
to `src\Iyzipay\DefaultHttpClient.php` line 41. At the end of the post function.

**Comment by kahvedigital** [comment]
Merhabalar,

Bu hatayı iletişim hatasında almaktasınız,

Curl fonksiyonlarının açık olduğundan emin olmalısınız 
curl_exec fonksiyonunun açık olması gerekmekte doruk.net gibi bazı server firmalarında kapalı olarak gelmektedir.
