### ISSUE TITLE
Windows Server Hatası

### ISSUE THREAD

**Issue by uguremir** [kahvedigital/iyzico-woocommerce#17]
Eğer woocommerce windows server üzerinde kurulu ise eklenti çalışmıyor, popup veya responsive hiç bir şekilde gelmiyor.

**Comment by kahvedigital** [comment]
Merhabalar,

CURL SSL verification ve curl_exec fonksiyonlarının kullanılabilir olduğundan emin olmalısınız. windows server üzerinde fonksiyonlar aktif olduğuna çalışmama gibi bir durum söz konusu değildir.
