### ISSUE TITLE
Wordpress 4.7.2 - Woocommerce 2.6.14 Error

### ISSUE THREAD

**Issue by uguryildirim** [kahvedigital/iyzico-woocommerce#2]
Hello,

I got this error every page;

`Warning: Declaration of WC_Gateway_Iyzicocheckoutform::process_refund($order_id, $amount = NULL) should be compatible with WC_Payment_Gateway::process_refund($order_id, $amount = NULL, $reason = '') in \wp-content\plugins\iyzico-woocommerce-master\class-wc-gateway-iyzico-checkout-form.php on line 99`

And i got second error after Billing Details (payment page) and cant continue:

`Catchable fatal error: Object of class Iyzipay\Model\CheckoutFormInitialize could not be converted to string in \wp-includes\pomo\entry.php on line 76`

Thanks

**Comment by heheok** [comment]
It is fixed with this commit: https://github.com/kahvedigital/iyzico-woocommerce/commit/6ef7cdf0b9bc97f7e5959be45017869c353d8c63

**Comment by uguryildirim** [comment]
Still got error:

Catchable fatal error: Object of class Iyzipay\Model\CheckoutFormInitialize could not be converted to string in \wp-includes\pomo\entry.php on line 76

![capture](https://cloud.githubusercontent.com/assets/16818522/23495744/1a1b119a-ff23-11e6-9430-f0151c8fec39.PNG)
