### ISSUE TITLE
Wordpress 4.7.2 - Woocommerce 2.6.14 Error 2

### ISSUE THREAD

**Issue by uguryildirim** [kahvedigital/iyzico-woocommerce#4]
Selam,

Önceki issue da belirtmiştim aslında. İkinci hata düzelmemiş. Ödeme sayfasında alttaki hatayı vermekte.

`Catchable fatal error: Object of class Iyzipay\Model\CheckoutFormInitialize could not be converted to string in \wp-includes\pomo\entry.php on line 76`

![capture](https://cloud.githubusercontent.com/assets/16818522/23496080/dfd2bf2c-ff24-11e6-86cc-518a8784df94.PNG)

**Comment by kahvedigital** [comment]
Merhabalar,

Öncelikle geri bilidiriminiz için çok teşekkür ederiz.
Hata ile ilgili detaylı inceleme ve düzeltme çalışmalarına başladık. En kısa sürede sizlere geri dönüş yapacağız.

**Comment by kahvedigital** [comment]
Merhabalar,
Belirtmiş olduğunuz hatanın detaylı kontrolünü sağladık.
Belirtmiş olduğunuz hatayı test ortamlarımızda rastlamadık ve hata oluştrabilecek tüm testlerimizi tamamladık. Dilerseniz sizin siteminiz üzerinde bir deneme yapabiliriz,
bize 0 dan bir wordpress kurup bilgileri ulaştırırsanız gerekli testleri sağlamış oluruz..

**Comment by uguryildirim** [comment]
İlginiz ve araştırmanız için teşekkür ederim. Test için sandbox api kullanıyorduk. Fakat class-wc-gateway-iyzico-checkout-form.php dosyasında api url enin prod api url i olduğunu gördüm. sandbox api url olarak değiştirince hata düzeldi. Settings kısmına bu ayar eklenebilirse çok daha güzel olur.

Zamanınızı ayırdğınız için tekrar teşekkür ederim.
