### ISSUE TITLE
Problem with variable products

### ISSUE THREAD

**Issue by dopplerDistortion** [kahvedigital/iyzico-woocommerce#7]
We have to use simple products option to sell virtual products. When we try to use variable product option then add a virtual product to it, iyzico payment gateway gives error about shipping adress. But virtual products don't have a shipping class. How can we solve it?

**Comment by kahvedigital** [comment]
Hello, in version 1.0.3 this bug due fixed.

**Comment by dopplerDistortion** [comment]
Thank you!
